version: '3.8'

services:
  ppt2code:
    build: .
    container_name: ppt2code-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Asia/Shanghai
    volumes:
      # 持久化存储
      - ./data/uploads:/app/uploads
      - ./data/converted:/app/converted
      - ./data/qrcodes:/app/qrcodes
      - ./data/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
