version: '3.8'

services:
  ppt2code:
    build: .
    container_name: ppt2code-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Asia/Shanghai
    volumes:
      # 持久化存储
      - ./uploads:/app/uploads
      - ./converted:/app/converted
      - ./qrcodes:/app/qrcodes
      - ./logs:/app/logs
      # 如果需要处理本地PPT文件，可以挂载目录
      - ./source-ppts:/app/source-ppts:ro
    networks:
      - ppt2code-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: ppt2code-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL证书目录
    depends_on:
      - ppt2code
    networks:
      - ppt2code-network

networks:
  ppt2code-network:
    driver: bridge

volumes:
  uploads:
  converted:
  qrcodes:
  logs:
